### ISSUE TITLE
UK keyboard layout request

### ISSUE THREAD

**Issue by roybarnard** [grml/grml-scripts#18]
I live in the UK and the lack of configuring a UK keyboard is frustrating and limits the number of people I can recommend GRML too.

In response to my contact email Darshaka suggested:
```
loadkeys i386/qwerty/uk.kmap.gz
```

I have tested this with `grml64-full_2020.06.iso` and that works perfectly (I checked every key on a standard Full UK Keyboard).

Please can "uk" be added to the keyboard selection.

Many Thanks
Roy Barnard

**Comment by mika** [comment]
Sorry for the late reply, @roybarnard but found some spare minutes today and implemented something™, I'd appreciate review of https://github.com/grml/grml-scripts/pull/19 and whether this looks like it should do the right thing™. :smile:

**Comment by roybarnard** [comment]
Thank you, I will test and report.
Many thanksRoy
    On Friday, 8 September 2023 at 08:57:15 BST, Michael Prokop ***@***.***> wrote:  
 
 


Sorry for the late reply, @roybarnard but found some spare minutes today and implemented something™, I'd appreciate review of #19 and whether this looks like it should do the right thing™. 😄
